FROM elasticsearch:5.0.0
MAINTAINER Eemil Väisänen <eemil.vaisanen@iki.fi>

ADD elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml

# RUN cd /usr/share/elasticsearch/ && ./bin/elasticsearch-plugin install -b x-pack
