version: '2'
services:
  prose:
    image: vaiski/prose
    ports:
      - 3000:3000
    environment:
      - OAUTH_CLIENT_ID=
      - GATEKEEPER_URL=http:\/\/127.0.0.1:9999

  gatekeeper:
    image: vaiski/gatekeeper
    ports:
      - 9999:9999
      - 8080:8080
    environment:
      - OAUTH_CLIENT_ID=
      - OAUTH_CLIENT_SECRET=
